name: check-build

on:
  push:
    branches:
      - 'feature/*'
      - 'master'
    paths:
      - 'server/**/*.txt'

jobs:
  is-build-target:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
