name: check-build

on:
  pull_request:
    branches:
      - 'feature/*'
      - 'master'
      - 'staging'
    paths:
      - './server/*'
    types: [closed]

jobs:
  is-build-target:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
