name: create_prod_pr

on:
  workflow_run:
    workflows: [auto-merge]
    branches:
      - staging
    types:
      - completed

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ahmadnassri/action-workflow-run-wait@v1
      - name: git-pr-release
        uses: bakunyo/git-pr-release-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: production
          GIT_PR_RELEASE_BRANCH_STAGING: staging