name: create_stg_pr

on:
  workflow_run:
    workflows: [test-mock]
    branches:
      - master
    types:
      - completed
  workflow_dispatch:

jobs:
  pr:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event.workflow_dispatch == true
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: git-pr-release
        uses: bakunyo/git-pr-release-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: staging
          GIT_PR_RELEASE_BRANCH_STAGING: master