name: create_stg_pr

on:
  workflow_run:
    workflows: [test-mock, test-mock2]
    branches:
      - master
    types:
      - completed
  workflow_dispatch:

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
            # test-php,test-js両方が完了していないと動かないようにするaction

      - id: wait
        uses: ahmadnassri/action-workflow-run-wait@v1
        with:
          # https://github.com/ahmadnassri/action-workflow-run-wait/tree/v1.4.4
          # 両方終了してないと続けたくない=最初に終了したワークフローの場合は即終了でいいのでtimeoutを1ミリ秒にする
          # 最後に終了したワークフローから発火するときは正常に動く
          timeout: 1
          
      # action-workflow-run-waitがtimeoutになった時の失敗はslack通知したくないので判定フラグ
      - id: is_workflow_timeout_check
        run: echo "::set-output name=IS_NOT_TIMEOUT::1"

      - name: git-pr-release
        uses: bakunyo/git-pr-release-action@281e1fe424fac01f3992542266805e4202a22fe0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: staging
          GIT_PR_RELEASE_BRANCH_STAGING: master
          # automergeアクションでこのラベルがついているものがマージされる
          GIT_PR_RELEASE_LABELS: automerge

      - if: steps.is_workflow_timeout_check.outputs.IS_NOT_TIMEOUT == '1' && failure()
        run: echo 1