name: create_stg_pr

on:
  workflow_call:
  # workflow_run:
  #   workflows: [test-mock, test-mock2]
  #   branches:
  #     - master
  #   types:
  #     - completed
  workflow_dispatch:

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      # - run: echo ${{ github.event.workflow_run.name }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: git-pr-release
        uses: bakunyo/git-pr-release-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: staging
          GIT_PR_RELEASE_BRANCH_STAGING: master

      - name: auto merge pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr merge master --merge

      - id: git-hash
        run: |
          echo "::set-output name=LATEST_HASH::$(git rev-parse --short origin/staging)"
  
      - run: echo ${{ steps.git-hash.outputs.LATEST_HASH }}
