name: create_stg_pr

on:
  workflow_call:
  # workflow_run:
  #   workflows: [test-mock, test-mock2]
  #   branches:
  #     - master
  #   types:
  #     - completed
  workflow_dispatch:

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      # - run: echo ${{ github.event.workflow_run.name }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      # https://github.com/marketplace/actions/create-pull-request
      - name: git-pr-release
        id: create_pull_request
        uses: peter-evans/create-pull-request@v4
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          base: staging
          labels: automerge

      - name: auto merge pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr merge ${{ steps.create_pull_request.outputs.pull-request-url }} --merge

      - id: git-hash
        run: |
          echo "::set-output name=LATEST_HASH::$(git rev-parse --short origin/staging)"
  
      - run: echo ${{ steps.git-hash.outputs.LATEST_HASH }}
