name: create_stg_pr

on:
  push:
    branches:
      - 'master'
    paths:
      - 'server/**/*.txt'

jobs:
  test1:
    uses: b54JP/test-github-actions/.github/workflows/test-mock.yml@master

  test2:
    uses: b54JP/test-github-actions/.github/workflows/test-mock2.yml@master

  pr-stg:
    uses: b54JP/test-github-actions/.github/workflows/create_stg_pr.yml@master
    needs: [test1, test2]

  pr-prod:
    uses: b54JP/test-github-actions/.github/workflows/create_prod_pr.yml@master
    needs: pr-stg

  deploy-stg:
    runs-on: ubuntu-latest
    needs: pr-stg
    outputs:
      NOTICE_SLACK: ${{ steps.notice-slack.outputs.NOTICE_SLACK }}
    steps:
      - id: notice-slack
        run: echo "::set-output name=NOTICE_SLACK::true"

  slack:
    runs-on: ubuntu-latest
    needs: deploy-stg
    if: always()
    steps:
      - uses: technote-space/workflow-conclusion-action@v1
      # Slack 通知用(成功時)
      - name: Slack Notification Success
        if: needs.deploy-stg.outputs.NOTICE_SLACK == 'true' && env.WORKFLOW_CONCLUSION == 'success'
        steps:
          - run: echo 'success'

      # Slack 通知用(失敗時)
      - name: Slack Notification Failure
        if: env.WORKFLOW_CONCLUSION == 'failure'
        steps:
          - run: echo 'failure'
      