name: create_stg_pr

on:
  push:
    branches:
      - 'master'
    # paths:
    #   - 'server/**/*.txt'

jobs:
  test1:
    uses: b54JP/test-github-actions/.github/workflows/test-mock.yml@master
    if: false

  test2:
    uses: b54JP/test-github-actions/.github/workflows/test-mock2.yml@master

  pr-stg:
    uses: b54JP/test-github-actions/.github/workflows/create_stg_pr.yml@master
    needs: [test1, test2]

  pr-prod:
    uses: b54JP/test-github-actions/.github/workflows/create_prod_pr.yml@master
    needs: pr-stg

  deploy-stg:
    runs-on: ubuntu-latest
    needs: pr-stg
    outputs:
      NOTICE_SLACK: ${{ steps.notice-slack.outputs.NOTICE_SLACK }}
    steps:
      - run: echo "::set-output name=NOTICE_SLACK::true"
      