name: deploy-mock-stg

on:
  workflow_run:
    workflows: [create_prod_pr]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: git-hash
        run: |
          echo "::set-output name=LATEST_HASH::$(git rev-parse --short origin/staging)"
      - run: echo ${{ steps.git-hash.outputs.LATEST_HASH }}