name: deploy-mock-stg

on:
  workflow_run:
    workflows: [auto-merge]
    branches:
      - master
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: staging
      - id: git-hash
        run: |
          echo "::set-output name=LATEST_HASH::$(git rev-parse --short origin/staging)"
      - run: echo ${{ steps.git-hash.outputs.LATEST_HASH }}