name: create_stg_pr

on:
  push:
    branches:
      - 'master'
    paths:
      - 'server/**/*.txt'

jobs:
  test1:
    uses: b54JP/test-github-actions/.github/workflows/test-mock.yml@master

  test2:
    uses: b54JP/test-github-actions/.github/workflows/test-mock2.yml@master

  pr-stg:
    uses: b54JP/test-github-actions/.github/workflows/create_stg_pr.yml@master
    needs: [test1, test2]

  pr-prod:
    uses: b54JP/test-github-actions/.github/workflows/create_prod_pr.yml@master
    needs: pr-stg

  deploy-stg:
    needs: pr-stg
    steps:
      - run: echo 1
      