name: create_stg_pr

on:
  push:
    branches:
      - 'master'
    paths:
      - 'server/**/*.txt'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      # - run: echo ${{ github.event.workflow_run.name }}
      - uses: actions/checkout@v3
  # test1:
  #   uses: b54JP/test-github-actions/.github/workflows/test-mock.yml@master
  #   needs: setup

  # test2:
  #   uses: b54JP/test-github-actions/.github/workflows/test-mock2.yml@master
  #   needs: setup

  merge:
    uses: b54JP/test-github-actions/.github/workflows/create_stg_pr.yml@master
    # needs: [test1, test2]
    needs: setup