# 本運用の時はtestが実行されるworkflowを想定
name: test-mock

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  if: github.event.pull_request.merged == true
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo test
