# 本運用の時はtestが実行されるworkflowを想定
name: test-mock

on:
  push:
    branches:
      - master
      - 'feature/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo test
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: test-mock2.yml
          name: commit-hash
          run_id: 1097141050