name: test-mock2

on:
  workflow_call:
  workflow_dispatch:

jobs:
  is-run-test:
    # https://docs.github.com/ja/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest
    outputs:
      TEST: ${{ steps.test.outputs.TEST }}
    steps:
      - uses: actions/checkout@v3
      - id: test
        run: |
          run_push=`git log -m -1 --name-only | grep "server/*" -c;`
          echo "::set-output name=TEST::$run_push"
  test:
    runs-on: ubuntu-latest
    needs: is-run-test
    if: needs.is-run-test.outputs.TEST != '0'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: commit-message
        run: |
          echo "::set-output name=COMMIT_MESSAGE::$(git log -1 --pretty=%B --abbrev-commit)"
        if: "!contains({{ step.commit-message.outputs.COMMIT_MESSAGE }}, '[skip test]')"
      - run: echo $(git rev-parse --short origin/master) > hash.txt
      - uses: actions/upload-artifact@v2
        with:
          name: commit-hash
          path: hash.txt

