name: test-mock2

on:
  workflow_call:
  workflow_dispatch:

jobs:
  is-run-test:
    # https://docs.github.com/ja/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest
    outputs:
      TEST: ${{ steps.test.outputs.TEST }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: test
        run: |
          run_push=`git log -m -1 --name-only | grep "server/*" -c;`
          echo "::set-output name=TEST::$run_push"
  test:
    runs-on: ubuntu-latest
    needs: is-run-test
    if: needs.is-run-test.outputs.TEST != '0'
    outputs:
      NOTICE_SLACK: ${{ steps.notice-slack.outputs.NOTICE_SLACK }}
    steps:
      - run: sleep 60
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: FALSE
      - id: notice-slack
        run: echo "::set-output name=NOTICE_SLACK::true"
      - run: echo $(git rev-parse --short origin/master) > hash.txt
      - uses: actions/upload-artifact@v2
        with:
          name: commit-hash
          path: hash.txt

