# 本運用の時はtestが実行されるworkflowを想定
name: test-mock

on:
  workflow_run:
    workflows: [check-build]
    branches:
      - master
      - staging
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo test