name: test-mock2

on:
  push:
    branches:
      - master
      - 'feature/*'

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      NOTICE_SLACK: ${{ steps.notice-slack.outputs.NOTICE_SLACK }}
    steps:
      - id: notice-slack
        run: echo "::set-output name=NOTICE_SLACK::true"

  slack-mock:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: needs.build-and-test.outputs.NOTICE_SLACK == 'true' && always()
    steps:
      - uses: technote-space/workflow-conclusion-action@v1
      # Slack 通知用(成功時)
      - name: Slack Notification Success
        if: env.WORKFLOW_CONCLUSION == 'success'
        run: echo ${{ needs.build-and-test.outputs.NOTICE_SLACK }}
      # Slack 通知用(失敗時)
      - name: Slack Notification Failure
        if: env.WORKFLOW_CONCLUSION == 'failure'
        run: echo ${{ needs.build-and-test.outputs.NOTICE_SLACK }}
