# 本運用の時はtestが実行されるworkflowを想定
name: test-mock

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: git-hash
        run: echo "::set-output name=LATEST_HASH::$(git rev-parse --short HEAD)"
      - run: echo ${{ steps.git-hash.outputs.LATEST_HASH }}